### ISSUE TITLE
Out of date package

### ISSUE THREAD

**Issue by bschousek** [Roboteurs/slushengine-modelx-lite#1]
This repository shows version 1.18 of the modelx-lite, with changes through August 2016. My recently received modelx-lite is a revision 1.28 with an October 2016 date. One difference appears to be a missing analog to digital converter. Are there other differences of interest?

**Comment by Mango-kid** [comment]
none of the slushengine model  lites have an analog to digial converter. The Slushengine lites are based on an NXP IO expander that does not have those features. They are currently only avalible on the model D.

**Comment by Mango-kid** [comment]
the repo will be updated shortly
